name: Build Renode Conan Package

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      CONAN_HOME: ~/.conan2/${{ matrix.os == 'macos-latest' && 'Macos' || 'Linux' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
      
      - name: Configure Conan profile
        run: |
          conan profile detect

      - name: create dotnet Package
        working-directory: dot_net
        run: |
          conan create .
          conan cache clean "*"

      - name: Install required python packages
        run: |
          pip install -r tests/requirements.txt
          pip install -r tools/csv2resd/requirements.txt
          pip install -r tools/execution_tracer/requirements.txt
          
      - name: Create Renode package
        run: conan create .
      
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: renode-artifacts-${{ matrix.os == 'macos-latest' && 'Macos' || 'Linux' }}
          path: ~/.conan2/${{ matrix.os == 'macos-latest' && 'Macos' || 'Linux' }}/*
          retention-days: 1