name: Build Renode Conan Package

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Add Conan remote
        run: |
          conan remote add conan-silabs-net https://conan-aus.silabs.net
          conan remote login conan-silabs-net buildengineer -p ${{ secrets.SVC_BUILDENGINEER }}

      - name: create dotnet Package
        working-directory: dot_net
        run: |
          conan create .

      - name: Upload dotnet package
        run: |
          conan upload dotnet_tools/8.0.409@silabs -r conan-silabs-net --confirm
      

      - name: Create Renode package
        run: conan create .

      - name: Upload package
        run: conan upload renode/1.15.3@silabs -r conan-silabs-net --confirm
          